language: ruby

jobs:
  include:
    - name: "Minimum supported versions"
      rvm: 2.4
      gemfile: Gemfile.rails52
    - name: "Latest released versions"
      rvm: 2.7
      gemfile: Gemfile
    - name: "Rails master branch"
      rvm: 2.7
      gemfile: Gemfile.rails_head

services:
  - mysql
